# Generated by Django 5.0.2 on 2024-04-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44, null=True)),
                ('natureza_operacao', models.CharField(blank=True, max_length=255, null=True)),
                ('cfop', models.CharField(blank=True, max_length=4, null=True)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_notas.categoria')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_recebidas', to='gestao_notas.destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='gestao_notas.nota')),
            ],
        ),
    ]
