# Generated by Django 5.0.2 on 2024-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
