# Generated by Django 5.0.2 on 2024-05-01 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_notas', '0002_nota_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
