# Generated by Django 5.0.2 on 2024-05-01 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_notas', '0003_nota_data_criacao_alter_nota_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['data_criacao']},
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('parcelas', models.IntegerField()),
                ('banco', models.CharField(max_length=255)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='gestao_notas.destinatario')),
            ],
        ),
        migrations.CreateModel(
            name='RecebimentoPagt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numero_parcela', models.IntegerField()),
                ('pago', models.BooleanField(default=False)),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='gestao_notas.recebimento')),
            ],
        ),
    ]
