# Generated by Django 5.0.2 on 2024-05-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_notas', '0004_alter_nota_options_recebimento_recebimentopagt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recebimento',
            options={'ordering': ['data_criacao']},
        ),
        migrations.AddField(
            model_name='destinatario',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='gestao_notas.cliente'),
            preserve_default=False,
        ),
    ]
