# Generated by Django 5.0.2 on 2024-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_notas', '0004_alter_destinatario_cpf_cnpj_alter_emitente_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnota',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemnota',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
