# Generated by Django 5.0.2 on 2024-04-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_notas', '0005_alter_itemnota_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateionota',
            old_name='ratio',
            new_name='valor',
        ),
    ]
